# Generated by Django 5.0.6 on 2024-08-13 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mm1', '0003_rename_department_semester_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='dept_name',
            new_name='semester',
        ),
    ]
