# Generated by Django 5.0.6 on 2024-08-13 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mm1', '0004_rename_dept_name_semester_semester'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Section',
            new_name='Selectsemester',
        ),
        migrations.RenameField(
            model_name='selectsemester',
            old_name='section_id',
            new_name='select_semester_id',
        ),
    ]
