# Generated by Django 5.0.6 on 2024-08-14 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm1', '0005_rename_section_selectsemester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credit_hours',
            field=models.IntegerField(default=3),
        ),
    ]
